name       : docbook2x
version    : 0.8.8
release    : 1
source     :
    - https://sourceforge.net/projects/docbook2x/files/docbook2x/0.8.8/docbook2X-0.8.8.tar.gz/download : 4077757d367a9d1b1427e8d5dfc3c49d993e90deabc6df23d05cfe9cd2fcdc45
license    : MIT
component  : programming.tools
summary    : docbook2X converts DocBook documents into man pages and Texinfo documents.
description: |
    docbook2X converts DocBook documents into man pages and Texinfo documents.
builddeps  :
    - perl-xml-sax-expat
rundeps    :
    - perl-xml-sax-expat
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
